### PR TITLE
Add Blue Exclamation Block and Change the Beep Block textures

### PR DESCRIPTION
**Pull request by komerish**

### CODE REVIEW

**Comment by Hugman76** [comment]
Why does the ! block have two side textures?
Also, you forgot about adding data for the ! block (loot table, tags)

**Comment by komerish** [comment]
The ! block is supposed to have two flipped sides so they line up. I guess you might want to flip them in the code though.
I'll add the loot table, etc. later.

**Comment by Hugman76** [comment]
Oh, the model itself can be changed in order for the flipped sides to appear actually. I can modify that tommorow in this very PR, if you want?

**Comment by komerish** [comment]
Hm, maybe just merge it for the new textures.

**Comment by Hugman76** [comment]
It seems textures for the two sides of the Exclamation Block do not have the same shades of blue

**Comment by Hugman76** [comment]
Ok nevermind that's just my eye

**Pull request merged**
